### ISSUE TITLE
vault-dev blueprint not runnable

### ISSUE THREAD

**Issue by sestegra** [shipyard-run/blueprints#10]
# Environment
macOS 10.15.7
shipyard 0.1.17
git 2.28.0
docker desktop 3.0.1

# Scenario
* Install shipyard with HomeBrew
* Run `vault-dev` blueprint:
```
$ shipyard run ./vault-dev
Running configuration from:  ./vault-dev

2020-12-16T09:48:58.650+0100 [INFO]  Creating Network: ref=public
2020-12-16T09:48:58.708+0100 [INFO]  Creating Container: ref=vault
2020-12-16T09:49:32.705+0100 [ERROR] Timeout wating for HTTP healthcheck: address=http://vault.container.shipyard.run:8200/

########################################################

Title Simple Vault Server
Author Nic Jackson

Simple Vault Dev Server

This blueprint defines 0 output variables.

You can set output variables as environment variables for your current terminal session using the following command:

eval $(shipyard env)

To list output variables use the command:

shipyard output
```

# Result
Shipyard run command returned an error about a timeout on not resolveable FQDN address.
In fact, `localhost` from `vaul.hcl` file is replaced by `vault.container.shipyard.run` but it's not resolvable by the host.

# Expected result
Shipyard run command should execute correctly.

**Comment by nicholasjackson** [comment]
Oh thanks @sestegra and sorry about this, I for some reason have not been getting notifications on this repo.  So we use a little DNS hack to enable hostnames, this is so we can do L7 routing in ingress. Looking at the error Vault has failed to start, a container can define a health check. Let me check this out.

**Comment by nicholasjackson** [comment]
@sestegra I have been looking into this but was partway through a new release.

Sadly I have not been able to replicate the issue, I have however added some functional tests to this blueprint in CI, these tests run nightly and are currently passing.

```
Run shipyard test vault-dev/
Feature: Vault Docker
  In order to test the Vault in Docker blueprint
  I should apply a blueprint which defines the setup
  and test the resources are created correctly

  Scenario: Single Container from Local Blueprint                           # /home/runner/work/blueprints/blueprints/vault-dev/test/vault.feature:6
    Given I have a running blueprint                                        # test.go:191 -> *CucumberRunner
    Then the following resources should be running                          # test.go:268 -> *CucumberRunner
      | name  | type      |
      | vault | container |
2021-02-21T16:10:35.257Z [INFO]  Destroy Container: ref=vault
    And a HTTP call to "http://localhost:8200/" should result in status 200 # test.go:356 -> *CucumberRunner
2021-02-21T16:10:35.451Z [INFO]  Destroy Network: ref=public

1 scenarios (1 passed)
3 steps (3 passed)
23.081687973s
```

I am wondering if this might have just been too aggressive a timeout and it taking time for the K8s cluster to download and setup the vault server.
